simp/pupmod-simp-pupmod

build/pupmod-pupmod.spec, manifests/master/base.pp, spec/spec_helper.rb
This pulls in the changes from when we switched over from the old
system.
SIMP-188 #comment Updated pupmod
=> (SIMP-188) Incorporating all of the gap material

.fixtures.yml, CHANGELOG, manifests/init.pp, metadata.json, spec/classes/init_spec.rb
SIMP-1177 #comment pupmod done
=> (SIMP-1177) Include haveged for entropy generation

CHANGELOG, build/rpm_metadata/requires, manifests/init.pp, metadata.json
SIMP-1177 #comment updated
SIMP-1186 #comment pupmod done
=> (SIMP-1186) Use_haveged is a global catalyst.

CHANGELOG, build/rpm_metadata/requires, metadata.json
=> (SIMP-2018) Update iptables dep version

metadata.json
=> (SIMP-2046) Fix version in metadata.json

CHANGELOG, build/rpm_metadata/requires, metadata.json
update requirements files for SIMP 6 bump
SIMP-2112 #comment
=> (SIMP-2112) Fix dependancies

.gitlab-ci.yml
* Add gitlabci.yml that does syntax, metadata, lint,
unit, and automated acceptance testing
SIMP-2346 #close
=> SIMP-2346 Add .gitlab-ci.yml to pupmod-simp-pupmod

CHANGELOG, manifests/master.pp, spec/classes/master_spec.rb
=> (SIMP-2532) Set trusted_server_facts to true

.fixtures.yml, data/common.yaml, manifests/pass_two.pp
=> (SIMP-2769) Add pam::access::rule for pe-activemq

.fixtures.yml, CHANGELOG, data/common.yaml, metadata.json
Add configuration map for the mom-replica. We still need to figure out
the source of the problem with the upstream vendor
SIMP-3031 #close
=> (SIMP-3031) Add configuration for the mom replica

.fixtures.yml, CHANGELOG, data/common.yaml, metadata.json
* Split puppet_enterprise::profile::puppetdb to look for
puppet_enterprise::profile::database for postgres
SIMP-3093 #close
=> (SIMP-3093) Split puppet_enterprise::profile::puppetdb with postgres

CHANGELOG, Gemfile, manifests/master/base.pp, manifests/master/sysconfig.pp, manifests/pass_two.pp, spec/classes/master/base_spec.rb, spec/defines/pass_two_spec.rb
=> (SIMP-3176) Remove `audit` metaparameter

build/rpm_metadata/requires
=> (SIMP-3489) pupmod: add puppetlabs puppet_authorization to rpm requires

CHANGELOG, metadata.json
SIMP-4401 #comment pupmod-simp-pupmod add missing inifile dep
=> (SIMP-4401) Add missing puppetlabs/inifile dep to metadata.json

.fixtures.yml, .gitlab-ci.yml, .puppet-lint.rc, .travis.yml, CHANGELOG, Gemfile, manifests/agent/cron.pp, metadata.json
Adjust code to eliminate lint warning
SIMP-4399 #comment Update pupmod tests with minor/patch deps changes
=> (SIMP-4399) Update tests with deps changes

CHANGELOG
- entries were not in chronological order
SIMP-4543 #comment pupmod module
=> (SIMP-4543) Changelog Updates

.fixtures.yml, .puppet-lint.rc, CHANGELOG, metadata.json, spec/acceptance/suites/default/01_puppet_server_spec.rb
SIMP-4941 #comment pupmod fixed
=> (SIMP-4941) Cleanup unneeded fixtures

CHANGELOG, templates/usr/local/sbin/simp_generate_types.epp
Discovered that permissions were not being set correctly when testing an
upgrade.
=> (SIMP-4989) Fix simp_generate_types issues

manifests/master.pp, manifests/master/autosign.pp, manifests/master/base.pp, manifests/master/fileserver_entry.pp, manifests/master/sysconfig.pp, spec/classes/master_spec.rb
Patch to fix patch permission issues with the last set of fixes.
=> (SIMP-MAINT) Fix path perms

CHANGELOG, manifests/conf.pp, manifests/init.pp, spec/classes/init_spec.rb
=> (SIMP-6820) Fix environment section

CHANGELOG, Gemfile, manifests/master.pp, spec/classes/master_spec.rb
[SIMP-7811] #close
[SIMP-7811]: https://simp-project.atlassian.net/browse/SIMP-7811
=> [SIMP-7811] Add mitigation for CVE-2020-7942

.github/workflows/pr_tests.yml, .gitlab-ci.yml, CHANGELOG, REFERENCE.md, manifests/init.pp, manifests/master.pp, manifests/master/sysconfig.pp, spec/unit/compliance_engine/compliance_engine_enforce_spec.rb
Fixed:
- pupmod::master::sysconfig had a logic error that was preventing
application
SIMP-9675 #close
=> (SIMP-9675) Fixed bug in pupmod::master::sysconfig

CHANGELOG, REFERENCE.md, manifests/master/sysconfig.pp, spec/classes/10_classes/master/data/puppetserver-j9-rcc-compile-1632.txt, spec/classes/10_classes/master/data/puppetserver-j9-rcc-compile-48.txt, spec/classes/10_classes/master/data/puppetserver-j9-rcc-monolithic-1632.txt, spec/classes/10_classes/master/data/puppetserver-j9-rcc-monolithic-48.txt, spec/classes/10_classes/master/data/puppetserver-j9-rcc-primary-1632.txt, spec/classes/10_classes/master/data/puppetserver-j9-rcc-primary-48.txt, spec/classes/10_classes/master/data/puppetserver-j9-tuning_overrides.txt, spec/classes/10_classes/master/data/puppetserver-j9.txt, spec/classes/10_classes/master/data/puppetserver.txt, templates/etc/sysconfig/puppetserver.epp
- Added pupmod::master::sysconfig::use_code_cache_flushing to reduce excessive
memory usage
[SIMP-8697] #close
[SIMP-8697]: https://simp-project.atlassian.net/browse/SIMP-8697
=> (SIMP-8697) Add code cache flushing

CHANGELOG, metadata.json
=> Support puppetlabs-inifile < 6

.github/workflows/tag_deploy.yml, CHANGELOG, functions/server_version.pp, metadata.json, spec/acceptance/suites/default/01_puppet_server_spec.rb, spec/classes/20_classes/master_spec.rb, spec/spec_helper.rb
These updates may include the following:
* Update Gemfile
* Add support for Puppet 8
* Drop support for Puppet 6
* Update module dependencies
=> [puppetsync] Updates for Puppet 8
