- build/pupmod-pupmod.spec
- templates/commands/crl_download.erb
The CRL download code used to restart after downloading the Puppet CRL.
This should not be done (and probably should not have been done then!).
SIMP-271 #close #comment Fix legacy CRL + httpd restart
> (SIMP-271) Don't restart httpd when CRL fetched

- .rspec
- .travis.yml
- Gemfile
- build/pupmod-pupmod.spec
- manifests/init.pp
- manifests/master.pp
- metadata.json
- spec/classes/agent/cron_spec.rb
- spec/classes/init_spec.rb
- spec/classes/master/base_spec.rb
- spec/classes/master/reports_spec.rb
- spec/classes/master_spec.rb
- spec/defines/master/autosign_spec.rb
- spec/defines/master/fileserver_entry_spec.rb
- spec/spec_helper.rb
- templates/commands/crl_download.erb
Before this commit, the use_fips logic required two variables and could
not be influenced with a parameter.  The module was also missing some
support files and used old versions of others.   This commit updates the
use_fips logic and modernizes the module structure to include better
support files (e.g., Gemfile, metadata.json) and current spec test
practices (e.g., expectations, simp-rspec-puppet-facts).
SIMP-353 #comment updated use_fips logic,
SIMP-353 #comment added pupmod::use_fips parameter
SIMP-353 #comment freshened up module practices (files, tests)
SIMP-353 #close
> (SIMP-353) Freshen up spec tests + use_fips logic

- manifests/init.pp
- manifests/master.pp
- spec/classes/init_spec.rb
- spec/classes/master_spec.rb
- templates/commands/crl_download.erb
- templates/etc/puppetserver/conf.d/web-routes.conf.erb
- templates/etc/puppetserver/conf.d/webserver.conf.erb
- templates/etc/puppetserver/logback.xml.erb
Fixes made:
- Removed OBE computation of ssldir in crl_download.erb, which
resulted in an erroneous URL.
- Fixed bug in FileAppender file configuration in logback.xml.erb.
- Removed OBE computation of ssldir in webserver.conf.erb.
- Removed OBE gem_home parameter from pupmod::master.
Also improved spec test coverage.
> (SIMP-1727) SIMP 6 crl_download.erb uses wrong URL

- manifests/init.pp
- spec/classes/agent/cron_spec.rb
- spec/classes/data/auditd.txt
- spec/classes/init_spec.rb
- spec/classes/master/base_spec.rb
- spec/classes/master/data/puppetserver.txt
- spec/classes/master/data/puppetserver_clear_environment_cache.txt
- spec/classes/master/data/puppetserver_reload.txt
- spec/classes/master/sysconfig_spec.rb
- spec/classes/master_spec.rb
- spec/classes/params_spec.rb
- spec/spec_helper.rb
- templates/puppet-auditd-rules.erb
* Increase spec test coverage to 100% of resources.
* Add some missing documentation
* clean up how some files are laid down (template instead of inline
content).
* clean up how spec test data is being passed in. It was previously
sensitive to indentation causing spurious spec failures.
* Flesh out some existing tests to hit more parameters.
SIMP-2418 #close
> (SIMP-2418) Increase code coverage up to 100%

- .fixtures.yml
- .gitignore
- data/common.yaml
- hiera.yaml
- manifests/conf.pp
- manifests/init.pp
- manifests/master.pp
- manifests/master/base.pp
- manifests/master/sysconfig.pp
- manifests/pass_two.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/classes/master/sysconfig_spec.rb
- spec/defines/data/moduledata.yaml
- spec/defines/pass_two_spec.rb
- spec/fixtures/hieradata/hiera.yaml
- spec/spec_helper.rb
* Create pupmod::pass_two defined type, that inspects
the existing catalog, and depending upon whether
any PE classes are included, reconfigures pupmod
to match
* Use pe_ini_subsetting for pupmod::master::sysconfig
* Always use the puppet group for both agents and
masters
* Fix auditd global catalyst
* Add module data, and add a class lookup hash
to specify firewall rules, users, and services
SIMP-2504 #close
> (SIMP-2504) Use PE node classification to configure pupmod

- templates/usr/local/bin/puppetagent_cron.erb
The shell script makes assumptions based upon behavior in older versions of Puppet. For instance, the puppet client service no longer returns in a process listing for 'puppetd'.
Also, I've found that sometimes a Puppet agent can become unresponsive ("hung") and the script doesn't take that scenario into account. It will not run as long as it thinks another catalog run is in progress.
This PR works in my environment, so I hope that the assumptions I've made work in other environments as well. One thing that probably needs to be "tweaked" is support for non Red Hat based systems (and newer Red Hat systems once service commands no longer redirect to systemctl). The service command is used within this script, as it was being used previously to this PR and I personally don't have any non-RHEL …
> [SIMP-2545] puppetagent_cron.sh needs updating

- spec/classes/master/data/puppetserver.txt
- templates/etc/sysconfig/puppetserver.erb
Fixed an oversight where extra_java_args was present in the pupmod::master::sysconfig manifest, but it wasn't referenced anywhere in the template.
> (SIMP-2679) Use extra_java_args from manifest

- manifests/master/sysconfig.pp
- spec/defines/pass_two_spec.rb
One of the few configuration changes we make to the puppetserver config
file is changing the temporary directory since /tmp is noexec. Add a
semver based conditional test, and a test matrix to make sure that it
parses pe_build as necessary.
SIMP-2745 #close
> (SIMP-2745) Fix tempdir on PE 2016.5.1

- CHANGELOG
- manifests/agent/cron.pp
- metadata.json
- spec/classes/agent/cron_spec.rb
- templates/usr/local/bin/puppetagent_cron.erb
- Updated puppetagent_cron:
-  Added `enable_agent` param so users can clearly specify when they wish
to forcibly enable the puppet agent.
-  Added `max_disable_time param`. Updated logic to determine when to
forcibly enable a puppet agent, and moved logic into cron.pp for
user-friendliness.
-  Set maxruntime default of 4 hours
SIMP-2817 #close
SIMP-2702 #comment updated puppetagent_cron
> (SIMP-2817) Updated puppetagent_cron

- CHANGELOG
- manifests/init.pp
- manifests/master.pp
- manifests/master/base.pp
- metadata.json
Add an 'package_ensure' parameter that allows the admin to specify the specific
version of puppet-agent or puppetserver they want the module to install.
SIMP-2972 #close
> (SIMP-2972) Add 'package_ensure' parameter to pupmod and pupmod::master

- CHANGELOG
- manifests/master/simp_auth.pp
This is a follow up to SIMP-3049 based on feedback to SIMP-3196.
SIMP-3285 #close
> (SIMP-3285) - Ensure legacy auth.conf is backed up

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/spec_helper.rb
- templates/commands/crl_download.erb
The puppet agent now automatically pulls down the CRL from the
puppetserver when needed, and the cron job is no longer needed.
See: https://docs.puppet.com/puppet/latest/configuration.html#hostcrl
SIMP-3265 #close
> (SIMP-3265) Remove CRL pull cron job

- CHANGELOG
- manifests/master/simp_auth.pp
- metadata.json
- spec/classes/master/simp_auth_spec.rb
The clients can not access the ca certs because the path is wrong in
the auth.conf.  It needs "/modules/" in it.  I update the krb5_files path also.
SIMP-3348 #close
> (SIMP-3348) Auth.conf updates

- CHANGELOG
- README.md
- metadata.json
- Updated the README with instructions to back up legacy auth.conf
and modify new auth.conf, need be.
SIMP-3283 #comment Modified README
> (SIMP-3283) auth.conf README updates

- .travis.yml
- CHANGELOG
- Gemfile
- manifests/init.pp
- spec/classes/agent/cron_spec.rb
- spec/classes/init_spec.rb
- spec/classes/master/base_spec.rb
- spec/classes/master/sysconfig_spec.rb
- spec/classes/master_spec.rb
- Added resource that ensures OBB CRL pull cron job is absent
- Updated to facter 2.5 and simp-rspec-puppet-facts 2.0.0
- Pinned version of bundler to a version that works when FIPS mode
is enabled
- Fixed tests that were hardcoded to specific  values,
instead of using the actual fact test values.
SIMP-3460 #close
> (SIMP-3460) pupmod: remove OBE CRL pull cron job

- .fixtures.yml
- CHANGELOG
- build/rpm_metadata/requires
- manifests/agent/cron.pp
- metadata.json
- spec/classes/agent/cron_spec.rb
Add SHA256-based option to generate the minute parameter for
a client's puppet agent cron from its IP address. This option
is intended mitigate the undesirable clustering of client puppet
agent runs, when the number of IPs to be transformed is less
than the minute range over which the randomization is requested
(60) and/or the client IPs are not linearly assigned.
> (SIMP-3280) Add SHA256-based random minute option to agent cron

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/init_spec.rb
This commit fixes an issue discovered when testing `poss` scenario
against non-SIMP factsets where the compile will fail because
`:selinux_config_mode` does not exist when `:selinux` is `false`.
SIMP-3835 #close
> (SIMP-3835) Fix `:selinux_config_mode` bug

- CHANGELOG
- manifests/master.pp
- manifests/master/simp_auth.pp
- spec/classes/master/simp_auth_spec.rb
- pupmod::master::simp_auth
- Allow tweaking `allow` and `deny` rules for supported keydist auth rules
SIMP-4508 #close
> (SIMP-4508) pupmod: Allow tweaking of auth allow/deny

- CHANGELOG
- manifests/master.pp
- metadata.json
- spec/classes/master/sysconfig_spec.rb
- spec/classes/master_spec.rb
Prior to this the service name for the Puppetserver was hard-coded to
the open source name, `puppetserver`.  Puppet Enterprise uses a
different name, however, so any resources that used that variable were
wrong.  This commit changes the variable assignment to use a selector
based on the parameter `pupmod::master::server_distribution`.
> (SIMP-4574) Make the master service name dynamic

- .fixtures.yml
- .travis.yml
- CHANGELOG
- Gemfile
- manifests/master/base.pp
- manifests/master/simp_auth.pp
- metadata.json
- spec/classes/master/simp_auth_spec.rb
- spec/classes/master_spec.rb
- spec/fixtures/hieradata/default.yaml
- spec/fixtures/hieradata/pe.yaml
- spec/fixtures/hieradata/pupmod_splay_is_true.yaml
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- Fix service name and related resources on Puppet Enterprise (PE)
- Fix `$tmpdir` setting on PE
- Fix Puppetserver service management on PE
- Fix default for pupmod::master::simp_auth::pki_cacerts_all_allow
- `certname` back to `*`
> Fix Puppet 5 spec tests

- CHANGELOG
- lib/facter/puppet_service_enabled.rb
- lib/facter/puppet_service_started.rb
- manifests/agent/cron.pp
- metadata.json
- spec/classes/agent/cron_spec.rb
- spec/classes/init_test_spec.rb
- spec/files/systemctl_status_off.txt
- spec/files/systemctl_status_on.txt
- spec/unit/facter/puppet_service_spec.rb
- templates/usr/local/bin/careful_puppet_service_shutdown.epp
- templates/usr/local/bin/puppetagent_cron.epp
- added a line to cron script to disable puppet service before
running puppet in cron mode.
- added exec to agent/cron manifest to make sure puppet service
was disabled before cron runs first time.
SIMP-4662 #close
SIMP-4811 #close
> (SIMP-4662) Disable puppet service if in cron mode

- templates/usr/local/sbin/simp_generate_types.epp
The code that prevents running on an environment that is already being
processed was missing the '%x' required for executing the process list
command
> (SIMP-4828) Fix issue in simp_generate_types

- CHANGELOG
- manifests/master/sysconfig.pp
- metadata.json
- spec/acceptance/suites/default/05_generate_types_spec.rb
- spec/classes/master/data/puppetserver.txt
- spec/classes/master/sysconfig_spec.rb
- spec/defines/pass_two_spec.rb
- templates/usr/local/sbin/simp_generate_types.epp
- Fixed bug in which the JAVA tmpdir path for the puppetserver was
incorrectly set.  This could cause puppetserver RPM upgrades to fail.
- Fixed bug in simp_generate_types whereby it was failing when a
directory path missing the trailing '/' was passed as a target path
SIMP-5021 #close
> (SIMP-5021) Incorrect JAVA tmpdir in pupmod::master::sysconfig

- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/classes/init_spec.rb
This change unconditionally manages the puppet service and removes the
(apparently) broken status logic.
SIMP-5337 #close
> (SIMP-5337) Properly manage the puppet service

- .travis.yml
- CHANGELOG
- manifests/master.pp
- metadata.json
- spec/classes/master_spec.rb
Puppet 5.5.7 [PUP-9158][0] removed the puppet.conf deprecation notices
for `ca_ttl`, but the `[master]` section's [`ca` setting remains
deprecated][1], causing `puppet bootstrap` and every subsequent puppet
run to emit warnings.
The `[master] ca` setting will be removed completely in Puppet
6, as puppetserver's trapperkeeper [will take over CA duties][2].
This patch:
- ensures `[master] ca` when Puppet < 5.5.6
- removes `[master] ca` when Puppet >= 6
- removes `[master] ca` when Puppet >= 5.5.6, unless `$ensure_ca` =
false (allowing users to explicitly disable the Puppet CA)
Note that, until the release of `puppet-agent 5.5.8`, there is another
bug ([PUP-9266][3]) where deprecation warnings will be emitted when
the setting is used in code, instead of just when `[master] ca` is set 
in …
> (SIMP-5456) Remove deprecated `[master] ca` 

- .travis.yml
- CHANGELOG
- manifests/master/generate_types.pp
- templates/etc/sysconfig/puppetserver.epp
- Fix warning about automatic data type munging in the puppet server
sysconfig template
- Add workaround for Puppet 5 background exec issue to the
generate_types exec
SIMP-5707 #close
> (SIMP-5707) Work around Puppet 5 exec issue

- CHANGELOG
- manifests/master/generate_types.pp
- metadata.json
- spec/classes/master/generate_types_spec.rb
Sets pupmod::master::generate_types: enable => false by default to fix
bug causing puppet servers to crash.
SIMP-5978 #comment temporary workaround for generate_types bug
> (SIMP-5978) Temporarily disable generate_types

- CHANGELOG
- manifests/master/base.pp
- metadata.json
- Update minimum version of inifile Puppet module to 2.5.0
- Fix dependency cycle in a full SIMP system that was introduced by
the new autorequire of the parent directory of an INI file in the
ini_setting type
SIMP-6211 #close
> (SIMP-6211) Fix dep cycle with inifile 2.5.0

- .travis.yml
- manifests/master/sysconfig.pp
- spec/classes/master/data/puppetserver-j9.txt
- spec/classes/master/data/puppetserver.txt
- spec/classes/master/sysconfig_spec.rb
- spec/defines/pass_two_spec.rb
- templates/etc/sysconfig/puppetserver.epp
This prevents the `flock unsupported or native support failed to load` error
when using `puppetserver gem install` with [`/tmp` mounted  `noexec`](https://puppet.com/docs/puppetserver/latest/known_issues.html#tmp-directory-mounted-noexec).
> Set JAVA_ARGS_CLI as well as JAVA_ARGS.

- CHANGELOG
- manifests/master/base.pp
- manifests/pass_two.pp
- spec/classes/master/base_spec.rb
- spec/defines/pass_two_spec.rb
No longer hardcode the puppet uid and puppet gid to 52.
These ids are no longer set via SIMP asset RPM %post
actions.  If this module assumes ids of 52 in the resources it
creates for the puppet user and group, `simp bootstrap` fails.
SIMP-6629 #close
> (SIMP-6629) puppet uid/gid wrong

- CHANGELOG
- manifests/master.pp
- metadata.json
- spec/classes/master_spec.rb
- templates/etc/puppetserver/conf.d/ca.conf.epp
I need the subject-alt-names param to bootstrap a new puppetserver; the auth-extensions param is just for completeness.
> (SIMP-6814) Add ca params for auth-extensions and subject-alt-names.

- templates/etc/sysconfig/puppetserver.epp
If you pass a fixed ram size, $java_max_memory is undefined and you get an empty -Xmx argument
_JAVA_ARGS="-Xms16384m -Xmx -Djava.io.tmpdir=/opt/puppetlabs/server/data/puppetserver/pserver_tmp "
> Bug:  $java_max_memory is not defined

- .fixtures.yml
- .travis.yml
- CHANGELOG
- functions/server_distribution.pp
- manifests/agent/cron.pp
- manifests/init.pp
- manifests/master.pp
- manifests/master/autosign.pp
- manifests/master/base.pp
- manifests/master/fileserver_entry.pp
- manifests/master/generate_types.pp
- manifests/master/install.pp
- manifests/master/service.pp
- manifests/master/simp_auth.pp
- manifests/master/sysconfig.pp
- manifests/pass_two.pp
- metadata.json
- spec/acceptance/suites/default/01_puppet_server_spec.rb
- spec/classes/master/base_spec.rb
- spec/classes/master/generate_types_spec.rb
- spec/classes/master/simp_auth_spec.rb
- spec/classes/master/sysconfig_spec.rb
- spec/classes/master_spec.rb
- spec/defines/pass_two_spec.rb
When installing puppetserver for the first time, the following resource ordering must be observed:
- `Service['puppetserver'] -> Exec['puppetserver_reload']`
- `Service['puppetserver'] ~> Exec['simp_generate_types']`
- `Puppet_authorization['/etc/puppetlabs/puppetserver/conf.d/auth.conf'] ~> Service['puppetserver']`
> Fix ordering problems on first installation of puppetserver.

- .fixtures.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/default/01_puppet_server_spec.rb
- Remove EPEL from node sets
- Use install_simp_repos() in lieu of repos in node sets
- Remove unused agent node in node sets
- Use correct branch for puppet-systemd in fixtures
SIMP-6919 #comment pupmod-simp-pupmod
SIMP-6949 #comment pupmod-simp-pupmod
> (SIMP-6919) Remove unnecessary EPEL repos in node sets

- CHANGELOG
- manifests/pass_two.pp
- spec/defines/pass_two_spec.rb
- Ensure that pupmod::pass_two does not conflict with the internal PE
configuration code for group ownership of puppet.conf
SIMP-3913 #comment fix PE conflict on puppet.conf
> (SIMP-3913) Remove conflict with internal PE code

- CHANGELOG
- manifests/init.pp
- manifests/master/simp_auth.pp
- manifests/pass_two.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/classes/master/simp_auth_spec.rb
* Removed Puppet CRL pull cron, which was previously deprecated
* Removed keydist rules that utilized the legacy pki module
SIMP-7333 #close
SIMP-7424 #close
> (SIMP-7333) Remove legacy and deprecated features

- .fixtures.yml
- .gitlab-ci.yml
- spec/classes/master/generate_types_spec.rb
- templates/etc/systemd/system/simp_generate_types.path.epp
Ensure that the simp_generate_types systemd path is enabled at boot
time.
SIMP-7573 #close
> (SIMP-7573) Fix simp_generate_types systemd path

- .fixtures.yml
- CHANGELOG
- manifests/master/generate_types.pp
- spec/classes/master/generate_types_spec.rb
This change adds a check for systemd when generate_types is disabled,
resolving an error with handling unit-files that was breaking compile
in EL6 nodes.
Also updates spec tests and fixtures for acceptance issues.
SIMP-7830 #close
> (SIMP-7830) Resolve systemd error on EL6

- .gitlab-ci.yml
- CHANGELOG
- REFERENCE.md
- functions/server_distribution.pp
- manifests/master.pp
- manifests/master/autosign.pp
- manifests/master/base.pp
- manifests/master/fileserver_entry.pp
- manifests/master/sysconfig.pp
- manifests/pass_two.pp
- metadata.json
- spec/classes/10_classes/master/base_spec.rb
- spec/classes/10_classes/master/sysconfig_spec.rb
- Puppet 6.19 renamed the master section to server in puppet.settings.
The code was updated to check the server section first and if that
was undefined check the master section.
SIMP-8623 #close
> (SIMP-8623) Bootstrap failing after 6.19 update

- CHANGELOG
- REFERENCE.md
- SIMP/compliance_profiles/checks.yaml
- manifests/init.pp
- manifests/master.pp
- manifests/master/generate_types.pp
- metadata.json
- spec/classes/20_classes/master_spec.rb
Fixed:
- Default to TLS1.2 only
- Use `certname` by default and fall back to `fqdn` for bolt, etc..
SIMP-8592 #close
SIMP-8655 #comment Default pupmod to TLS1.2
> (SIMP-8592) Default to certname

- CHANGELOG
- REFERENCE.md
- manifests/init.pp
- metadata.json
- spec/classes/20_classes/init_spec.rb
This patch:
* Fixes a bug ([`certname` comes from $trusted, not $facts][0])
* Adds logic to use `certname` ONLY for authenticated remote
requests
* Uses `facts['clientcert']`, then `$facts['fqdn']` as a fallback
[0]: https://puppet.com/docs/puppet/6.17/lang_facts_builtin_variables.html
[SIMP-8592] #close #comment {{certname}} is a trusted fact
[SIMP-8592]: https://simp-project.atlassian.net/browse/SIMP-8592
> (SIMP-8592) certname is a trusted fact

- .github/workflows/pr_glci.yml
- .github/workflows/pr_glci_manual.yml
- .github/workflows/pr_tests.yml
- .gitlab-ci.yml
This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9325] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-pupmod
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-pupmod
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …
> (SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-pupmod

- .fixtures.yml
hocon 1.1.0 and puppet_authorization 0.5.1 were included in
SIMP 6.5.0 and are the latest versions available
[SIMP-9281] #comment pupmod-simp-pupmod
[SIMP-9281]: https://simp-project.atlassian.net/browse/SIMP-9281
> (SIMP-9281) pupmod: Test with latest module versions

- CHANGELOG
- REFERENCE.md
- manifests/init.pp
- spec/classes/20_classes/init_spec.rb
- spec/unit/compliance_engine/compliance_engine_enforce_spec.rb
- Changed
- Default pupmod::set_environment to `false` so that users don't accidentally
end up with systems in the wrong environment
SIMP-9608 #close
> (SIMP-9608) Default pupmod::set_environment to false

- .github/workflows/tag_deploy.yml
- .gitlab-ci.yml
This patch updates the GHA `tag_release` workflow to build and attach a
signed RPM to each GitHub release.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may apply other updates to ensure conformity.
[SIMP-10115] #close
[SIMP-10073] #comment Add GHA RPM release to pupmod-simp-pupmod
[SIMP-10115]: https://simp-project.atlassian.net/browse/SIMP-10115
[SIMP-10073]: https://simp-project.atlassian.net/browse/SIMP-10073
> (SIMP-10073) GHA: Add signed RPM to Github release

- CHANGELOG
Remove blank lines that causes information to be missed when
the tag changelog is generated.
> (SIMP-MAINT) pupmod Remove invalid blanks line within CHANGELOG entries

- CHANGELOG
- manifests/conf.pp
- manifests/master.pp
- spec/acceptance/suites/default/01_puppet_server_spec.rb
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-compile-1632.txt
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-compile-48.txt
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-monolithic-1632.txt
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-monolithic-48.txt
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-primary-1632.txt
- spec/classes/10_classes/master/data/puppetserver-j9-rcc-primary-48.txt
- spec/classes/10_classes/master/data/puppetserver-j9-tuning_overrides.txt
- spec/classes/10_classes/master/data/puppetserver-j9.txt
- spec/classes/10_classes/master/data/puppetserver.txt
- spec/classes/20_classes/master_spec.rb
- spec/defines/conf_spec.rb
- templates/etc/sysconfig/puppetserver.epp
* Fixed
- Change all instances of pupmod::master adding items to the `master` section to
use `server` instead
- Update pupmod::conf to automatically switch `master` to `server`
- Automatically remove items from the puppet config in the `master` section that
are set in the `server` section
SIMP-10399 #close
> (SIMP-10399) Change all `master` configs to `server`

- .gitignore
- CHANGELOG
- metadata.json
This patch updates from camptocamp/systemd 2.x to puppet/systemd 3.x
This bump is driven by simp/simp-core#829
> Update deps to use puppet/systemd

- .gitignore
- REFERENCE.md
- spec/classes/20_classes/init_spec.rb
This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.
> Finalize RockyLinux 8 support

- CHANGELOG
- manifests/agent/cron.pp
- metadata.json
The puppet_agent.timer systemd unit does not restart after a system reboots. The timer will restart when it is linked to timers.target.
> Add a [Install] for puppet_agent.timer (#186)

- CHANGELOG
- REFERENCE.md
- manifests/init.pp
- manifests/master/simp_auth.pp
- metadata.json
- spec/classes/20_classes/init_spec.rb
- templates/etc/puppetserver/conf.d/puppetserver.conf.epp
This should allow users to install `openvox-agent` instead of `puppet-agent`.
Fixes #192
> Add agent_package parameter
